"""create initial tables

Revision ID: 534d72b39dad
Revises: 
Create Date: 2026-09-15 23:22:27.952519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534d72b39dad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('en_route_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'missions', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'missions', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'missions', 'rescue_teams', ['team_id'], ['id'])
    op.add_column('tickets', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'completed_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'missions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'missions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_column('missions', 'cancelled_at')
    op.drop_column('missions', 'completed_at')
    op.drop_column('missions', 'arrived_at')
    op.drop_column('missions', 'en_route_at')
    # ### end Alembic commands ###
